using System;
using System.Collections.Generic;

#nullable disable

namespace HVFaceManagement.Models
{
    public partial class TblEmpInfo
    {
        public byte ComId { get; set; }
        public long AEmpId { get; set; }
        public long EmpId { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string EmpNameB { get; set; }
        public string EmpFather { get; set; }
        public string EmpFatherB { get; set; }
        public string EmpMother { get; set; }
        public string EmpMotherB { get; set; }
        public string EmpSpouse { get; set; }
        public string EmpSpouseB { get; set; }
        public string EmpCurrAdd { get; set; }
        public string EmpCurrVill { get; set; }
        public string EmpCurrPo { get; set; }
        public string EmpCurrPs { get; set; }
        public short EmpCurrDistId { get; set; }
        public string EmpPerAdd { get; set; }
        public string EmpPerVill { get; set; }
        public string EmpPerPo { get; set; }
        public string EmpPerPs { get; set; }
        public string EmpPerCity { get; set; }
        public short EmpPerDistId { get; set; }
        public string EmpPerZip { get; set; }
        public string EmpPhone { get; set; }
        public string EmpMobile { get; set; }
        public string EmpEmail { get; set; }
        public string EmpPicLocation { get; set; }
        public string EmpRemarks { get; set; }
        public string Sex { get; set; }
        public string Religion { get; set; }
        public string Caste { get; set; }
        public string BloodGroup { get; set; }
        public string MaritalSts { get; set; }
        public DateTime? DtBirth { get; set; }
        public DateTime? DtJoin { get; set; }
        public DateTime? DtReleased { get; set; }
        public DateTime? DtIncrement { get; set; }
        public byte IsConfirm { get; set; }
        public DateTime? DtConfirm { get; set; }
        public long ConfDay { get; set; }
        public short DeptId { get; set; }
        public short SectId { get; set; }
        public short SubSectId { get; set; }
        public short SectIdSal { get; set; }
        public int DesigId { get; set; }
        public short? SalId { get; set; }
        public string Grade { get; set; }
        public string Floor { get; set; }
        public string Line { get; set; }
        public string Band { get; set; }
        public string BandIncen { get; set; }
        public string SubBandIncen { get; set; }
        public string GradeIns { get; set; }
        public string Category { get; set; }
        public string WorkPlace { get; set; }
        public decimal Ts { get; set; }
        public decimal Gs { get; set; }
        public decimal Bs { get; set; }
        public decimal Ma { get; set; }
        public decimal Hr { get; set; }
        public decimal Trn { get; set; }
        public decimal PrdBn { get; set; }
        public string ShiftType { get; set; }
        public string ShiftCat { get; set; }
        public short? ShiftId { get; set; }
        public string Nationality { get; set; }
        public string PassportNo { get; set; }
        public string VoterNo { get; set; }
        public string BirthCertNo { get; set; }
        public byte IsAllowOtherAll { get; set; }
        public byte IsAllowNight { get; set; }
        public byte IsAllowAttBns { get; set; }
        public decimal AttBnsAmt { get; set; }
        public byte IsAllowHolidayBns { get; set; }
        public byte IsAllowPf { get; set; }
        public DateTime? DtPf { get; set; }
        public byte IsAllowOt { get; set; }
        public byte IsAllowPp { get; set; }
        public string PolicyNo { get; set; }
        public byte IsAllowGp { get; set; }
        public decimal Gpamt { get; set; }
        public byte IsTrnDeduction { get; set; }
        public byte IsInactive { get; set; }
        public byte? IsAllowGradebns { get; set; }
        public byte? IsAllowShortfall { get; set; }
        public string PaySource { get; set; }
        public string PayMode { get; set; }
        public string EmpType { get; set; }
        public string EmpSts { get; set; }
        public string CardNo { get; set; }
        public short BankId { get; set; }
        public string BankAcNo { get; set; }
        public int RefId { get; set; }
        public string Fpid { get; set; }
        public byte? WeekDayId { get; set; }
        public decimal? MobileAllow { get; set; }
        public decimal IncomeTax { get; set; }
        public decimal? PrevGross { get; set; }
        public string BusStop { get; set; }
        public byte IsTiffin { get; set; }
        public byte IsIncenBonus { get; set; }
        public byte IsSalary { get; set; }
        public decimal OtherAllow { get; set; }
        public short? ShiftIdR { get; set; }
        public string OfficeGrade { get; set; }
        public string Operation { get; set; }
        public string OldEmpId { get; set; }
        public string RegNo { get; set; }
        public string Kpitype { get; set; }
        public short Cdid { get; set; }
        public bool Approved { get; set; }
        public string Gse { get; set; }
        public string Bse { get; set; }
        public string OtherAllowE { get; set; }
        public byte MngType { get; set; }
        public byte IsVehicle { get; set; }
        public int? AId { get; set; }
        public Guid WId { get; set; }
        public string Pcname { get; set; }
        public short? LuserId { get; set; }
        public string CadreType { get; set; }
        public byte IsAllowOtstaff { get; set; }
        public decimal OtallowAmt { get; set; }
        public decimal OffDayAllowAmt { get; set; }
        public string NickName { get; set; }
        public string EmpReplace { get; set; }
        public DateTime? DtApprove { get; set; }
        public int? ChildNo { get; set; }
        public string EmpCurrDist { get; set; }
        public string EmpPerDist { get; set; }
        public decimal ShiftAllow { get; set; }
        public decimal IncenBns { get; set; }
        public string EduLvl { get; set; }
        public byte IsMaternity { get; set; }
        public string EmpRef { get; set; }
        public string EmpRefMob { get; set; }
        public byte IsTax { get; set; }
        public byte IsAcc { get; set; }
        public string EmpCurrZip { get; set; }
        public string EmpCurrCity { get; set; }
        public DateTime? DtTransport { get; set; }
        public byte IsAllowOtno { get; set; }
        public byte IsDisabled { get; set; }
        public byte IsDormitoryFacility { get; set; }
        public byte IsOffDayOt { get; set; }
        public string EmpNomineeName { get; set; }
        public string EmpNomineeMob { get; set; }
        public string EmergencyName { get; set; }
        public string EmergencyMob { get; set; }
        public string EmpTinno { get; set; }
        public string EmployementType { get; set; }
        public string EmpCatagory { get; set; }
        public string Team { get; set; }
        public string Zone { get; set; }
        public string DesigFirst { get; set; }
        public decimal Gsstart { get; set; }
        public short BranchId { get; set; }
        public decimal CashSalary { get; set; }
        public string Title { get; set; }
        public DateTime? DtCardAssign { get; set; }
        public string IncrSession { get; set; }
        public DateTime? DtOtentitled { get; set; }
        public string SkillGradePoint { get; set; }
        public byte IsNonSmv { get; set; }
        public byte IsContract { get; set; }
        public byte IsUpdateData { get; set; }
        public string WorkType { get; set; }
        public string WorkTypeB { get; set; }
        public string EmpSon { get; set; }
        public string EmpDaughter { get; set; }
        public string EmpFatherMobileNo { get; set; }
        public string EmpMotherMobileNo { get; set; }
        public string EmpSpouseMobileNo { get; set; }
        public string EmpSonMobileNo { get; set; }
        public string EmpDaughterMobileNo { get; set; }
        public string EmpFatherAdd { get; set; }
        public string EmpMotherAdd { get; set; }
        public string EmpSpouseAdd { get; set; }
        public string EmpSonAdd { get; set; }
        public string EmpDaughterAdd { get; set; }
        public string EmpFatherEmail { get; set; }
        public string EmpMotherEmail { get; set; }
        public string EmpSpouseEmail { get; set; }
        public string EmpSonEmail { get; set; }
        public string EmpDaughterEmail { get; set; }
        public DateTime? DtFatherBirth { get; set; }
        public DateTime? DtMotherBirth { get; set; }
        public DateTime? DtSpouseBirth { get; set; }
        public DateTime? DtSonBirth { get; set; }
        public DateTime? DtDaughterBirth { get; set; }
        public DateTime? DtMarrige { get; set; }
        public string DrivingLicenseNo { get; set; }
        public string VehicleDetails { get; set; }
        public DateTime? DtPissue { get; set; }
        public DateTime? DtPexpiry { get; set; }
        public DateTime? DtPplaceIssue { get; set; }
        public DateTime? DtDissue { get; set; }
        public DateTime? DtDexpiry { get; set; }
        public byte IsTwvehicle { get; set; }
        public byte IsFwvehicle { get; set; }
        public string EmpSpectacles { get; set; }
        public string SexB { get; set; }
        public string CardNoOld { get; set; }
        public byte IsNid { get; set; }
        public byte IsLitigation { get; set; }
        public byte IsLitigationP { get; set; }
        public string EmpBehavior { get; set; }
        public string EmpKnowledge { get; set; }
        public string LitigationDetails { get; set; }
        public float ChildM { get; set; }
        public float ChildF { get; set; }
        public DateTime? DtSubmit { get; set; }
    }
}
