// <auto-generated />
using System;
using HVFaceManagement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HIKDeviceManagement.Migrations
{
    [DbContext(typeof(GTRDBContext))]
    partial class GTRDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HVFaceManagement.Models.HR_Emp_DeviceInfoHIK", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cardNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("empImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("empName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("fingerData")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("id");

                    b.ToTable("HR_Emp_DeviceInfoHIK");
                });

            modelBuilder.Entity("HVFaceManagement.Models.HR_MachineNoHIK", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hikpassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hikuser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsActive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("LuserId")
                        .HasColumnType("smallint");

                    b.Property<string>("Pcname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HR_MachineNoHIK");
                });

            modelBuilder.Entity("HVFaceManagement.Models.HrRawDatum", b =>
                {
                    b.Property<int>("AId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DtPunchDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtPunchTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmpId")
                        .HasColumnType("int");

                    b.Property<string>("Fpid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imei")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InOut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsNew")
                        .HasColumnType("int");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LuserId")
                        .HasColumnType("int");

                    b.Property<string>("OvNmark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pcname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PicBack")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PicFront")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Qrdata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StNo")
                        .HasColumnType("int");

                    b.HasKey("AId");

                    b.ToTable("HR_RawData");
                });
#pragma warning restore 612, 618
        }
    }
}
